version: '2.1'

networks:
  kong-net:
    name: kong-net-int

services:
  kong-migrations:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-ee-mig-int
    command: kong migrations bootstrap
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: password
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
    networks:
      - kong-net
    restart: on-failure

  kong:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-ee-int
    user: "${KONG_USER:-kong}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8003
      KONG_PORTAL_API_LISTEN: 0.0.0.0:8004
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_VITALS: "on"
      KONG_PORTAL: "on"
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: "basic-auth"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_ADMIN_API_URI: "http://localhost:8001"
      KONG_ADMIN_GUI_SESSION_CONF: '{"secret":"mysecret","cookie_name":"kong_cookie","storage":"cookie","cookie_lifetime":3600,"cookie_renew":600,"cookie_secure":false,"cookie_samesite":"off"}'
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8010:8010/tcp"
      - "8002:8002/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    
  db:
    image: postgres:9.5
    container_name: kong-db-int
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net

  httpbin:
    container_name: httpbin-int
    image: "kennethreitz/httpbin"
